services:
  database:
    image: postgres:15
    container_name: myapp_postgres
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myapp_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:

# docker exec -it myapp_postgres psql -U my_user -d myapp_db

